

Program("main", ["main.c"],
	CPPPATH = [],		#include head file
	LIBS = ["wiringPi"],	#lib
	LIBPATH = [],		#lib path
	CCFLASS = ["-g", "-Wall"]	#encode args
)


#Example
'''
Program("main", ["main.cpp", "librplidar_sdk.a"],
	CPPPATH = ["include"],
	LIBS = [],
	LIBAPTH = [],
	CCFLASS = ["-g", "-o3", "-Wall"]
)
'''
	
